#ifndef c
#define c

#include<math.h>

#define INPUTIMAGESIZE 28
#define NUMBEROFKERNELS 10
#define KERNELSIZE 7
//#define EXPECTEDSIZE 22
#define TENSORSIZE 49
//#define NUMBEROFTENSOR 10
#define BIASSIZE 10
#define FLATTENSIZE TENSORSIZE*NUMBEROFKERNELS
#define CONVOLUTEDSIZE 22
#define STRIFESIZE 3
//#define NUMBEROFKERNELS 10
#define POOLEDSIZE 7
//#define STRIFESIZE 3
#endif
